on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn
      - run: yarn lint

  tsc:
    runs-on: ubuntu-latest
    name: Check TypeScript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn
      - run: yarn tsc
  
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn
      - name: Unit Tests
        run: yarn test:unit
